services:
  backend:
    container_name: meal-planner-backend
    build:
      context: ./backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB:-tiki_meal_planner}
      PORT: 3000
    restart: unless-stopped
    networks:
      - tiki-net
      - pg_network

  frontend:
    container_name: meal-planner-frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - tiki-net

networks:
  tiki-net:
  pg_network:
    external: true
    name: pg_network
